version: "3.8"
services:
  qemu:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - DISPLAY=:1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "6080:80"
    tty: true