build TARGET_ARCH = X64 TOOL_CHAIN_TAG = GCC ACTIVE_PLATFORM = OvmfPkg/OvmfPkgX64.dsc -DSECURE_BOOT_ENABLE=FALSE -DBUILD_SHELL=TRUE -DNETWORK_TLS_ENABLE=TRUE -DTPM2_ENABLE=TRUE -DSMM_REQUIRE=FALSE

Build/OvmfX64/RELEASE_GCC5/FV/