//      **AUTO-GENERATED SCRIPT**
#include "InterruptRoutines.h"

void InitIDT(idtENTRY_t *IDT, uint16_t limit, uint16_t CodeSegment){
    idtDESC_t temp = {.table = IDT, .limit = limit};
    LoadIDT(&temp);
	InitInterrupt(0, true, ISR_INTERRUPT0, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(1, true, ISR_INTERRUPT1, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(2, true, ISR_INTERRUPT2, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(3, true, ISR_INTERRUPT3, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(4, true, ISR_INTERRUPT4, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(5, true, ISR_INTERRUPT5, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(6, true, ISR_INTERRUPT6, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(7, true, ISR_INTERRUPT7, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(8, true, ISR_INTERRUPT8, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(9, true, ISR_INTERRUPT9, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(10, true, ISR_INTERRUPT10, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(11, true, ISR_INTERRUPT11, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(12, true, ISR_INTERRUPT12, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(13, true, ISR_INTERRUPT13, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(14, true, ISR_INTERRUPT14, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(15, true, ISR_INTERRUPT15, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(16, true, ISR_INTERRUPT16, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(17, true, ISR_INTERRUPT17, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(18, true, ISR_INTERRUPT18, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(19, true, ISR_INTERRUPT19, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(20, true, ISR_INTERRUPT20, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(21, true, ISR_INTERRUPT21, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(22, true, ISR_INTERRUPT22, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(23, true, ISR_INTERRUPT23, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(24, true, ISR_INTERRUPT24, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(25, true, ISR_INTERRUPT25, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(26, true, ISR_INTERRUPT26, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(27, true, ISR_INTERRUPT27, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(28, true, ISR_INTERRUPT28, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(29, true, ISR_INTERRUPT29, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(30, true, ISR_INTERRUPT30, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(31, true, ISR_INTERRUPT31, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(32, true, ISR_INTERRUPT32, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(33, true, ISR_INTERRUPT33, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(34, true, ISR_INTERRUPT34, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(35, true, ISR_INTERRUPT35, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(36, true, ISR_INTERRUPT36, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(37, true, ISR_INTERRUPT37, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(38, true, ISR_INTERRUPT38, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(39, true, ISR_INTERRUPT39, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(40, true, ISR_INTERRUPT40, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(41, true, ISR_INTERRUPT41, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(42, true, ISR_INTERRUPT42, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(43, true, ISR_INTERRUPT43, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(44, true, ISR_INTERRUPT44, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(45, true, ISR_INTERRUPT45, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(46, true, ISR_INTERRUPT46, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(47, true, ISR_INTERRUPT47, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(48, true, ISR_INTERRUPT48, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(49, true, ISR_INTERRUPT49, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(50, true, ISR_INTERRUPT50, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(51, true, ISR_INTERRUPT51, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(52, true, ISR_INTERRUPT52, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(53, true, ISR_INTERRUPT53, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(54, true, ISR_INTERRUPT54, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(55, true, ISR_INTERRUPT55, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(56, true, ISR_INTERRUPT56, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(57, true, ISR_INTERRUPT57, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(58, true, ISR_INTERRUPT58, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(59, true, ISR_INTERRUPT59, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(60, true, ISR_INTERRUPT60, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(61, true, ISR_INTERRUPT61, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(62, true, ISR_INTERRUPT62, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(63, true, ISR_INTERRUPT63, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(64, true, ISR_INTERRUPT64, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(65, true, ISR_INTERRUPT65, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(66, true, ISR_INTERRUPT66, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(67, true, ISR_INTERRUPT67, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(68, true, ISR_INTERRUPT68, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(69, true, ISR_INTERRUPT69, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(70, true, ISR_INTERRUPT70, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(71, true, ISR_INTERRUPT71, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(72, true, ISR_INTERRUPT72, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(73, true, ISR_INTERRUPT73, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(74, true, ISR_INTERRUPT74, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(75, true, ISR_INTERRUPT75, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(76, true, ISR_INTERRUPT76, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(77, true, ISR_INTERRUPT77, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(78, true, ISR_INTERRUPT78, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(79, true, ISR_INTERRUPT79, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(80, true, ISR_INTERRUPT80, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(81, true, ISR_INTERRUPT81, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(82, true, ISR_INTERRUPT82, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(83, true, ISR_INTERRUPT83, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(84, true, ISR_INTERRUPT84, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(85, true, ISR_INTERRUPT85, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(86, true, ISR_INTERRUPT86, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(87, true, ISR_INTERRUPT87, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(88, true, ISR_INTERRUPT88, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(89, true, ISR_INTERRUPT89, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(90, true, ISR_INTERRUPT90, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(91, true, ISR_INTERRUPT91, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(92, true, ISR_INTERRUPT92, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(93, true, ISR_INTERRUPT93, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(94, true, ISR_INTERRUPT94, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(95, true, ISR_INTERRUPT95, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(96, true, ISR_INTERRUPT96, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(97, true, ISR_INTERRUPT97, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(98, true, ISR_INTERRUPT98, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(99, true, ISR_INTERRUPT99, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(100, true, ISR_INTERRUPT100, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(101, true, ISR_INTERRUPT101, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(102, true, ISR_INTERRUPT102, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(103, true, ISR_INTERRUPT103, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(104, true, ISR_INTERRUPT104, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(105, true, ISR_INTERRUPT105, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(106, true, ISR_INTERRUPT106, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(107, true, ISR_INTERRUPT107, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(108, true, ISR_INTERRUPT108, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(109, true, ISR_INTERRUPT109, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(110, true, ISR_INTERRUPT110, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(111, true, ISR_INTERRUPT111, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(112, true, ISR_INTERRUPT112, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(113, true, ISR_INTERRUPT113, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(114, true, ISR_INTERRUPT114, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(115, true, ISR_INTERRUPT115, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(116, true, ISR_INTERRUPT116, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(117, true, ISR_INTERRUPT117, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(118, true, ISR_INTERRUPT118, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(119, true, ISR_INTERRUPT119, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(120, true, ISR_INTERRUPT120, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(121, true, ISR_INTERRUPT121, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(122, true, ISR_INTERRUPT122, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(123, true, ISR_INTERRUPT123, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(124, true, ISR_INTERRUPT124, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(125, true, ISR_INTERRUPT125, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(126, true, ISR_INTERRUPT126, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(127, true, ISR_INTERRUPT127, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(128, true, ISR_INTERRUPT128, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(129, true, ISR_INTERRUPT129, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(130, true, ISR_INTERRUPT130, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(131, true, ISR_INTERRUPT131, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(132, true, ISR_INTERRUPT132, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(133, true, ISR_INTERRUPT133, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(134, true, ISR_INTERRUPT134, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(135, true, ISR_INTERRUPT135, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(136, true, ISR_INTERRUPT136, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(137, true, ISR_INTERRUPT137, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(138, true, ISR_INTERRUPT138, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(139, true, ISR_INTERRUPT139, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(140, true, ISR_INTERRUPT140, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(141, true, ISR_INTERRUPT141, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(142, true, ISR_INTERRUPT142, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(143, true, ISR_INTERRUPT143, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(144, true, ISR_INTERRUPT144, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(145, true, ISR_INTERRUPT145, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(146, true, ISR_INTERRUPT146, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(147, true, ISR_INTERRUPT147, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(148, true, ISR_INTERRUPT148, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(149, true, ISR_INTERRUPT149, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(150, true, ISR_INTERRUPT150, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(151, true, ISR_INTERRUPT151, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(152, true, ISR_INTERRUPT152, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(153, true, ISR_INTERRUPT153, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(154, true, ISR_INTERRUPT154, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(155, true, ISR_INTERRUPT155, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(156, true, ISR_INTERRUPT156, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(157, true, ISR_INTERRUPT157, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(158, true, ISR_INTERRUPT158, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(159, true, ISR_INTERRUPT159, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(160, true, ISR_INTERRUPT160, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(161, true, ISR_INTERRUPT161, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(162, true, ISR_INTERRUPT162, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(163, true, ISR_INTERRUPT163, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(164, true, ISR_INTERRUPT164, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(165, true, ISR_INTERRUPT165, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(166, true, ISR_INTERRUPT166, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(167, true, ISR_INTERRUPT167, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(168, true, ISR_INTERRUPT168, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(169, true, ISR_INTERRUPT169, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(170, true, ISR_INTERRUPT170, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(171, true, ISR_INTERRUPT171, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(172, true, ISR_INTERRUPT172, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(173, true, ISR_INTERRUPT173, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(174, true, ISR_INTERRUPT174, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(175, true, ISR_INTERRUPT175, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(176, true, ISR_INTERRUPT176, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(177, true, ISR_INTERRUPT177, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(178, true, ISR_INTERRUPT178, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(179, true, ISR_INTERRUPT179, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(180, true, ISR_INTERRUPT180, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(181, true, ISR_INTERRUPT181, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(182, true, ISR_INTERRUPT182, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(183, true, ISR_INTERRUPT183, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(184, true, ISR_INTERRUPT184, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(185, true, ISR_INTERRUPT185, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(186, true, ISR_INTERRUPT186, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(187, true, ISR_INTERRUPT187, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(188, true, ISR_INTERRUPT188, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(189, true, ISR_INTERRUPT189, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(190, true, ISR_INTERRUPT190, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(191, true, ISR_INTERRUPT191, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(192, true, ISR_INTERRUPT192, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(193, true, ISR_INTERRUPT193, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(194, true, ISR_INTERRUPT194, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(195, true, ISR_INTERRUPT195, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(196, true, ISR_INTERRUPT196, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(197, true, ISR_INTERRUPT197, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(198, true, ISR_INTERRUPT198, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(199, true, ISR_INTERRUPT199, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(200, true, ISR_INTERRUPT200, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(201, true, ISR_INTERRUPT201, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(202, true, ISR_INTERRUPT202, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(203, true, ISR_INTERRUPT203, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(204, true, ISR_INTERRUPT204, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(205, true, ISR_INTERRUPT205, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(206, true, ISR_INTERRUPT206, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(207, true, ISR_INTERRUPT207, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(208, true, ISR_INTERRUPT208, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(209, true, ISR_INTERRUPT209, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(210, true, ISR_INTERRUPT210, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(211, true, ISR_INTERRUPT211, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(212, true, ISR_INTERRUPT212, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(213, true, ISR_INTERRUPT213, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(214, true, ISR_INTERRUPT214, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(215, true, ISR_INTERRUPT215, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(216, true, ISR_INTERRUPT216, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(217, true, ISR_INTERRUPT217, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(218, true, ISR_INTERRUPT218, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(219, true, ISR_INTERRUPT219, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(220, true, ISR_INTERRUPT220, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(221, true, ISR_INTERRUPT221, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(222, true, ISR_INTERRUPT222, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(223, true, ISR_INTERRUPT223, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(224, true, ISR_INTERRUPT224, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(225, true, ISR_INTERRUPT225, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(226, true, ISR_INTERRUPT226, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(227, true, ISR_INTERRUPT227, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(228, true, ISR_INTERRUPT228, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(229, true, ISR_INTERRUPT229, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(230, true, ISR_INTERRUPT230, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(231, true, ISR_INTERRUPT231, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(232, true, ISR_INTERRUPT232, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(233, true, ISR_INTERRUPT233, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(234, true, ISR_INTERRUPT234, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(235, true, ISR_INTERRUPT235, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(236, true, ISR_INTERRUPT236, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(237, true, ISR_INTERRUPT237, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(238, true, ISR_INTERRUPT238, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(239, true, ISR_INTERRUPT239, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(240, true, ISR_INTERRUPT240, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(241, true, ISR_INTERRUPT241, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(242, true, ISR_INTERRUPT242, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(243, true, ISR_INTERRUPT243, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(244, true, ISR_INTERRUPT244, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(245, true, ISR_INTERRUPT245, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(246, true, ISR_INTERRUPT246, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(247, true, ISR_INTERRUPT247, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(248, true, ISR_INTERRUPT248, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(249, true, ISR_INTERRUPT249, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(250, true, ISR_INTERRUPT250, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(251, true, ISR_INTERRUPT251, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(252, true, ISR_INTERRUPT252, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(253, true, ISR_INTERRUPT253, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(254, true, ISR_INTERRUPT254, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
	InitInterrupt(255, true, ISR_INTERRUPT255, CodeSegment, 
            IDTFLAGS_RING0 | IDTFLAGS32B_INTRGATE | IDTFLAGS_PRESENT);
}
