#pragma once

#include "kernel/services/USB/service.h"
//*	http://www.o3one.org/hwdocs/usb/hcir1_0a.pdf

#define HcRhPortStatus(N)		(0x50 + (sizeof(uint32_t) * (N)))
enumdef(uint16_t, OHCIHubRegister){
	//	Host Controller revision number
	HcRevision = 0x00, 
	//	Operating modes & execution state controls
	HcControl = 0x04, 
	//	Host Controller commands & status flags
	HcCommandStatus = 0x08, 
	//	Pending interrupt events (Write-1-to-Clear)
	HcInterruptStatus = 0x0C, 
	//	Interrupt generation enable mask
	HcInterruptEnable = 0x10, 
	//	Interrupt generation disable mask
	HcInterruptDisable = 0x14, 
	//	Physical address of HCCA structure (256-byte aligned)
	HcHCCA = 0x18, 
	//	Physical address of current periodic Endpoint Descriptor (ED)
	HcPeriodCurrentEndpointDescriptor = 0x1C, 
	//	Head pointer for Control list ED chain
	HcControlHeadEndpointDescriptor = 0x20, 
	//	Current pointer in Control list ED chain
	HcControlCurrentEndpointDescriptor = 0x24, 
	//	Head pointer for Bulk list ED chain
	HcBulkHeadEndpointDescriptor = 0x28, 
	//	Current pointer in Bulk list ED chain
	HcBulkCurrentEndpointDescriptor = 0x2C, 
	//	Head pointer of completed Transfer Descriptor (TD) queue
	HcDoneHead = 0x30, 
	//	Bit timing interval & max packet size parameters
	HcFrameInterval = 0x34, 
	//	Bit countdown counter for remaining frame time
	HcFrameRemaining = 0x38, 
	//	16-bit frame number counter (fixed duplicate entry)
	HcFrameNumber = 0x3C, 
	//	Frame time threshold where periodic ED list starts processing
	HcPeriodicStart = 0x40, 
	//	Low-speed bit threshold for packet transmission cutoff
	HcLSThreshold = 0x44, 
	//	Root Hub Descriptor A (Port count, power switching attributes)
	HcRootHubDescriptorA = 0x48, 
	//	Root Hub Descriptor B (Port removable flags & power masks)
	HcRootHubDescriptorB = 0x4C, 
	//	Root Hub status & global power control
	HcRootHubStatus = 0x50, 
	HcRootHubPortStatus = 0x54
};
#define OHCIRegisterStruct(R)	__packed OHCI##R##Register_t

typedef struct{uint32_t	Revision	: 8;	uint32_t	: 24;}OHCIRegisterStruct(HcRevision);
enumdef(uint8_t, OHCIHcControlFunctionalState){USBReset = 0b00, USBResume = 0b01, USBOperational = 0b10, USBSuspend = 0b11};
typedef struct{
	//	This specifies the service ratio between Control and Bulk EDs.
	uint32_t	ControlBulkServiceRatio			: 2;
	//	This bit is set to enable the processing of the periodic list in the next Frame.
	uint32_t	PeriodicListEnable				: 1;
	//	This bit is used by HCD to enable/disable processing of isochronous EDs.
	uint32_t	IsochronousEnable				: 1;
	//	This bit is set to enable the processing of the Control list in the next Frame.
	uint32_t	ControlListEnable				: 1;
	//	This bit is set to enable the processing of the Bulk list in the next Frame.
	uint32_t	BulkListEnable					: 1;
	uint32_t	HostControllerFunctionalState	: 2;
	//	This bit determines the routing of interrupts generated by events registered in HcInterruptStatus.
	uint32_t	InterruptRouting				: 1;
	//	This bit indicates whether HC supports remote wakeup signaling.
	//	If remote wakeup is supported and used by the system it is the
	//		responsibility of system firmware to set this bit during POST.
	uint32_t	RemoteWakeupConnected			: 1;
	//	This bit is used by HCD to enable or disable the remote wakeup
	//		feature upon the detection of upstream resume signaling
	uint32_t	RemoteWakeupEnable				: 1;
	uint32_t									: 21;
}OHCIRegisterStruct(HcControl);
typedef struct{
	//	This bit is set by HCD to initiate a software reset of HC.
	uint32_t	HostControllerReset		: 1;
	//	This bit is used to indicate whether there are any TDs on the Control list. 
	//	It is set by HCD whenever it adds a TD to an ED in the Control list.
	uint32_t	ControlListFilled		: 1;
	uint32_t	BulkListFilled			: 1;
	uint32_t	OwnershipChangeRequest	: 1;
	uint32_t							: 12;
	//	These bits are incremented on each scheduling overrun error. 
	//	It is initialized to 00b and wraps around at 11b.
	uint32_t	SchedulingOverrunCount	: 2;
	uint32_t							: 14;
}OHCIRegisterStruct(HcCommandStatus);
typedef struct{
	uint32_t	SchedulingOverrunEnable		: 1;
	uint32_t	HcDoneHeadWritebackEnable	: 1;
	uint32_t	StartOfFrameEnable			: 1;
	uint32_t	ResumeDetectEnable			: 1;
	uint32_t	UnrecoverableErrorEnable	: 1;
	uint32_t	FrameNumberOverflowEnable	: 1;
	uint32_t	RootHubStatusChangeEnable	: 1;
	uint32_t								: 23;
	uint32_t	OwnershipChangeEnable		: 1;
	//	A '1' written to this field enables interrupt generation 
	//	due to events specified in the other bits of this register.
	uint32_t	HcInterruptEnable			: 1;
}OHCIRegisterStruct(HcInterruptEnable);
typedef struct{
	uint32_t	SchedulingOverrunDisable	: 1;
	uint32_t	HcDoneHeadWritebackDisable	: 1;
	uint32_t	StartOfFrameDisable			: 1;
	uint32_t	ResumeDetectDisable			: 1;
	uint32_t	UnrecoverableErrorDisable	: 1;
	uint32_t	FrameNumberOverflowDisable	: 1;
	uint32_t	RootHubStatusChangeDisable	: 1;
	uint32_t								: 23;
	uint32_t	OwnershipChangeDisable		: 1;
	//	A '1' written to this field enables interrupt generation 
	//	due to events specified in the other bits of this register.
	uint32_t	HcInterruptDisable			: 1;
}OHCIRegisterStruct(HcInterruptDisable);
typedef struct{
	uint32_t	SchedulingOverrun	: 1;
	uint32_t	HcDoneHeadWriteback	: 1;
	uint32_t	StartOfFrame		: 1;
	uint32_t	ResumeDetect		: 1;
	uint32_t	UnrecoverableError	: 1;
	uint32_t	FrameNumberOverflow	: 1;
	uint32_t	RootHubStatusChange	: 1;
	uint32_t						: 23;
	uint32_t	OwnershipChange		: 1;
	//	A '1' written to this field enables interrupt generation 
	//	due to events specified in the other bits of this register.
	uint32_t						: 1;
}OHCIRegisterStruct(HcInterruptStatus);
//	The HcHCCA register contains the physical address of the Host Controller Communication Area.
typedef uint32_t OHCIRegisterStruct(HcHCCA);
//	The HcPeriodCurrentED register contains the physical address of the current Isochronous or Interrupt Endpoint Descriptor.
typedef uint32_t OHCIRegisterStruct(HcPeriodCurrentEndpointDescriptor);
//	The HcControlHeadED register contains the physical address of the first Endpoint Descriptor of the Control list.
typedef uint32_t OHCIRegisterStruct(HcControlHeadEndpointDescriptor);
//	The HcControlCurrentED register contains the physical address of the current Endpoint Descriptor of the Control list.
typedef uint32_t OHCIRegisterStruct(HcControlCurrentEndpointDescriptor);
//	The HcBulkHeadED register contains the physical address of the first Endpoint Descriptor of the Bulk list.
typedef uint32_t OHCIRegisterStruct(HcBulkHeadEndpointDescriptor);
//	The HcBulkCurrentED register contains the physical address of the current endpoint of the Bulk list.
typedef uint32_t OHCIRegisterStruct(HcBulkCurrentEndpointDescriptor);
//	The HcDoneHead register contains the physical address of the last completed Transfer Descriptor that was added to the Done queue.
typedef uint32_t OHCIRegisterStruct(HcDoneHead);
typedef struct{
	//	This specifies the interval between two consecutive SOFs in bit times.
	uint32_t	FrameInterval		: 14;
	uint32_t						: 2;
	//	This field specifies a value which is loaded into the Largest 
	//		Data Packet Counter at the beginning of each frame.
	uint32_t	FSLargestDataPacket	: 15;
	uint32_t	FrameIntervalToggle	: 1;
}OHCIRegisterStruct(HcFrameInterval);
typedef struct{
	//	This counter is decremented at each bit time.
	uint32_t	FrameRemaining		: 14;
	uint32_t						: 17;
	//	This bit is loaded from the FrameIntervalToggle field of 
	//		HcFmInterval whenever FrameRemaining reaches 0.
	uint32_t	FrameRemainingToggle: 1;
}OHCIRegisterStruct(HcFrameRemaining);
typedef struct{
	//	his is incremented when HcFmRemaining is re-loaded.
	uint32_t	FrameNumber			: 16;
	uint32_t						: 16;
}OHCIRegisterStruct(HcFrameNumber);
typedef struct{
	uint32_t	PeriodicStart		: 14;
	uint32_t						: 18;
}OHCIRegisterStruct(HcPeriodicStart);
typedef struct{
	//	This field contains a value which is compared to the FrameRemaining field prior to initiating a Low Speed transaction. 
	//	The transaction is started only if FrameRemaining >= this field
	uint32_t	LSThreshold			: 12;
	uint32_t						: 20;
}OHCIRegisterStruct(HcLSThreshold);

typedef struct{
	uint32_t	NumberDownstreamPorts		: 8;
	uint32_t	PowerSwitchingMode			: 1;
	uint32_t	NoPowerSwitching			: 1;
	uint32_t	DeviceType					: 1;
	uint32_t	OverCurrentProtectionMode	: 1;
	uint32_t	NoOverCurrentProtection		: 1;
	uint32_t								: 10;
	//	This byte specifies the duration HCD has to wait before
	//		accessing a powered-on port of the Root Hub.
	//	The duration is calculated as POTPGT * 2 ms.
	uint32_t	PowerOnToPowerGoodTime		: 8;
}OHCIRegisterStruct(HcRootHubDescriptorA);
typedef struct{
	uint32_t	DeviceRemovableBitmask		: 16;
	uint32_t	PortPowerControlMaskBitmask	: 16;
}OHCIRegisterStruct(HcRootHubDescriptorB);
typedef struct{
	uint32_t	LocalPowerStatus			: 1;
	uint32_t	OverCurrentIndicator		: 1;
	uint32_t								: 13;
	uint32_t	DeviceRemoteWakeupEnable	: 1;
	uint32_t	LocalPowerStatusChange		: 1;
	uint32_t	OverCurrentIndicatorChange	: 1;
	uint32_t								: 13;
	uint32_t	ClearRemoteWakeupEnable		: 1;
}OHCIRegisterStruct(HcRootHubStatus);
typedef struct{
	uint32_t	CurrentConnectStatus			: 1;
	uint32_t	PortEnableStatus				: 1;
	uint32_t	PortSuspendStatus				: 1;
	//	This bit is only valid when the Root Hub is configured in such a
	//		way that overcurrent conditions are reported on a per-port basis.
	//	0 = no overcurrent condition.
	//	1 = overcurrent condition detected.
	uint32_t	PortOverCurrentIndicator		: 1;
	uint32_t	PortResetStatus					: 1;
	uint32_t									: 3;
	uint32_t	PortPowerStatus					: 1;
	uint32_t	LowSpeedDeviceAttached			: 1;
	uint32_t									: 6;
	uint32_t	ConnectStatusChange				: 1;
	uint32_t	PortEnableStatusChange			: 1;
	uint32_t	PortSuspendStatusChange			: 1;
	uint32_t	PortOverCurrentIndicatorChange	: 1;
	uint32_t	PortResetStatusChange			: 1;
	uint32_t									: 11;
}OHCIRegisterStruct(HcRootHubPortStatus);

enumdef(uint8_t, OHCIEndpointDescriptorDataFlow){
	GetDirectionFromTD = 0b00, DeviceToHostDataFlow = 0b01, 
	HostToDeviceDataFlow = 0b10, GetDirectionFromTD = 0b11
};
typedef struct{
	//	This is the USB address of the function containing the endpoint that this ED controls.
	uint32_t	FunctionAddress				: 7;
	//	This is the USB address of the endpoint within the function.
	uint32_t	EndpointAddress				: 4;
	uint32_t	DataFlow					: 3;
	uint32_t	LowSpeedEndpoint			: 1;
	uint32_t	Skip						: 1;
	uint32_t	IsochronousTransfers		: 1;
	uint32_t	MaximumPacketSize			: 10;
	uint32_t								: 5;
	uint32_t	TransferDescriptorQueueTail;
	uint32_t	QueueHalted					: 1;
	uint32_t	Carry						: 1;
	uint32_t								: 2;
	//	Shift assignment down by 4
	uint32_t	TransferDescriptorQueueHead	: 28;
	uint32_t	NextEndpointDescriptor;
}__packed OHCIEndpointDescriptor_t;
typedef struct{
	uint32_t								: 16;
	//	The last packet may be smaller than the buffer size without causing an error 
	uint32_t	PreviousPacketErrorDisable	: 1;
	//	00b: SETUP
	//	01b: OUT
	//	10b: IN
	uint32_t	TransferDirection			: 2;
	//	number of frames to wait after processing this TD and before sending an interrupt, 
	//		a value of 111b means there is no interrupt for this TD.
	uint32_t	FrameDelay					: 4;
	uint32_t	DataToggle					: 2;
	uint32_t	ErrorCount					: 4;
	uint32_t	LastTransactionStataus		: 4;
	uint32_t	BufferPointer;
	uint32_t	NextTransferDescriptor;
	uint32_t	BufferTipPointer;
}__packed OHCITransferDescriptor_t;
typedef struct{
	//	Interrupt ED list pointers.
	uint32_t HccaInterruptTable[32];
	//	Current 16-bit frame number.
	uint16_t HccaFrameNumber;
	//	Reserved.
	uint16_t HccaPad1;
	//	Head pointer of completed TDs.
	uint32_t HccaDoneHead;
	uint8_t  Reserved[116];
}OHCIRegisterStruct(_HcHCCA);

typedef struct{
	CommonMutex Mtx;
	struct OHCIInterruptCommand *Next;
}OHCIInterruptCommand;
typedef struct{
	void *acpibase;
	uint32_t N;
	OHCIInterruptCommand Command;
}__packed OHCIInterruptStackHeader;

ISRCallbackDefinition(OHCIHeadDone){
	OHCIInterruptStackHeader *SH = Frame->StackHeader;
	OHCIHcInterruptStatusRegister_t IS = {0};
	OHCI_HcHCCARegister_t *HCCA = NULL;
	if(OHCIReadU32(SH->acpibase, SH->N, HcHCCA, (uint32_t *)&HCCA) && OHCIReadU32(SH->acpibase, SH->N, HcInterruptStatus, (uint32_t *)&IS)){
		if(IS.HcDoneHeadWriteback){
			uint32_t done_head_raw = HCCA->HccaDoneHead;
			HCCA->HccaDoneHead = 0;

			IS = (OHCIHcInterruptStatusRegister_t){0};	IS.HcDoneHeadWriteback = true;
			OHCIWriteU32(SH->acpibase, SH->N, HcInterruptStatus, (uint32_t *)&IS);

			uint32_t curr_phys = done_head_raw & ~0xFU;
			while(curr_phys != 0){
				OHCITransferDescriptor_t *td = (OHCITransferDescriptor_t *)MapVirtual(curr_phys);
				if(!td){break;}

				//	Save physical pointer to next completed TD in the chain
				uint32_t next_phys = td->NextTransferDescriptor & ~0xFU;

				//	Check Condition Code (0x0 = No Error, 0x4 = Stalled, 0xF = Active)
				uint8_t completion_code = td->LastTransactionStataus;

				if(completion_code == 0){/*Transfer completed successfully*/}else
				{/*Error occurred (e.g. CRC error, Stall, Device Not Responding)*/}

				//	Free completed descriptor memory
				FreePages(td);
				curr_phys = next_phys;
			}
		}
		OHCIInterruptCommand *Temp = &(SH->Command), *Previous = Temp;
		while(Temp->Next){Previous = Temp;	Temp = Temp->Next;}
		Previous->Next = NULL;
		UnlockMutex(Temp->Mtx);
	}
}

bool OHCIReadU32(void *acpibase, uint32_t N, OHCIHubRegister R, uint32_t *Out){
	uint32_t bus, slot;
	PCIDevice *d = PCIeSearchDevice(acpibase, GetPCIstruct(SerialBus_USB_OHCI), N, &bus, &slot);
	if(d->HeaderType.Type == PCIGeneralDevice){
		PCIHeader0x0 *_0x0 = (PCIHeader0x0 *)d;
		if(_0x0->BAR[0].IOBAR.IsIOSpace){*Out = __inl(_0x0->BAR[0].IOBAR._4ByteAlignedAddress);
		}else{*Out = *((uint32_t *)MapVirtual(_0x0->BAR[0].MSBAR._16ByteAlignedAddress) + R);}
		return true;
	}
	return false;
}

bool OHCIWriteU32(void *acpibase, uint32_t N, OHCIHubRegister R, uint32_t Data){
	uint32_t bus, slot;
	PCIDevice *d = PCIeSearchDevice(acpibase, GetPCIstruct(SerialBus_USB_OHCI), N, &bus, &slot);
	if(d->HeaderType.Type == PCIGeneralDevice){
		PCIHeader0x0 *_0x0 = (PCIHeader0x0 *)d;
		if(_0x0->BAR[0].IOBAR.IsIOSpace){__outw(_0x0->BAR[0].IOBAR._4ByteAlignedAddress, Data);
		}else{*(uint32_t *)(MapVirtual(_0x0->BAR[0].MSBAR._16ByteAlignedAddress) + R) = Data;}
		return true;
	}
	return false;
}

bool ConfigureOHCIController(void *acpibase, uint32_t IOAPIC, uint32_t N, uint8_t Privilege){
	//	Enable PCI MMIO Space and Bus Mastering
	uint32_t bus, slot;
	PCIDevice *d = PCIeSearchDevice(acpibase, GetPCIstruct(SerialBus_USB_OHCI), N, &bus, &slot);
	if(!d){return false;}

	//	Update IOAPIC Redirection
	uint8_t IV;
	IOAPICInterruptRegister IR = ReadIoApicInterruptRegister(acpibase, IOAPIC, ((PCIHeader0x0 *)d)->InterruptLine);
	AllocateInterruptVector(&IV);
	IR.Register.Vector = IV;
	WriteIoApicInterruptRegister(acpibase, IOAPIC, ((PCIHeader0x0 *)d)->InterruptLine, IR);
	
	//	Enable Memory Space (bit 1) and Bus Master (bit 2) in PCI Command Register
	d->Command.MemorySpace = true;
	d->Command.BusMaster = true;

	//	Read existing Frame Interval parameters
	OHCIHcFrameIntervalRegister_t fm_interval = {0};
	OHCIReadU32(acpibase, N, HcFrameInterval, (uint32_t *)&fm_interval);
	//	Preserved Frame Interval (typically 0x2EDF / 11,999)

	//	Issue Host Controller Reset
	OHCIWriteU32(acpibase, N, HcCommandStatus, 0x01); // Set HostControllerReset bit
	
	//	Wait for reset to complete (bit auto-clears within 10 microseconds)
	uint32_t status = 0;
	do{OHCIReadU32(acpibase, N, HcCommandStatus, &status);}while(status & 0x01);

	//	Restore Timing Registers
	// Calculate Max Largest Frame Packet Size (FSMPS) based on FI
	fm_interval.FSLargestDataPacket = (((fm_interval.FrameInterval - 210) * 6 / 7) & 0x7FFF);
	OHCIWriteU32(acpibase, N, HcFrameInterval, *((uint32_t *)&fm_interval));
	OHCIWriteU32(acpibase, N, HcPeriodicStart, (fm_interval.FrameInterval * 9) / 10); // Set periodic start to 90% of FI

	//	Allocate and Register HCCA (Must be 256-Byte Physically Aligned)
	OHCI_HcHCCARegister_t *hcca = AllocateAlignedPagesFromRange(NULL, UINT32_MAX, sizeof(OHCI_HcHCCARegister_t), (ReadWritable | SupervisorMode), 0x00, 256);
	OHCIWriteU32(acpibase, N, HcHCCA, (uint32_t)(uintptr_t)MapPhysical(hcca));

	//	Clear Head Registers
	OHCIWriteU32(acpibase, N, HcControlHeadEndpointDescriptor, 0);
	OHCIWriteU32(acpibase, N, HcBulkHeadEndpointDescriptor, 0);

	//	Configure Controller Interrupt Mask
	//	Clear all stale pending interrupts (Write 1 to Clear)
	OHCIWriteU32(acpibase, N, HcInterruptStatus, 0x7FFFFFFF);

	//	Enable selected events and Master Interrupt Enable (MIE = Bit 31)
	OHCIHcInterruptEnableRegister_t IR = {
		.FrameNumberOverflowEnable = true, .HcDoneHeadWritebackEnable = true, .HcInterruptEnable = true, 
		.OwnershipChangeEnable = true, .ResumeDetectEnable = true, .RootHubStatusChangeEnable = true, 
		.SchedulingOverrunEnable = true, .StartOfFrameEnable = true, .UnrecoverableErrorEnable = true
	};
	OHCIWriteU32(acpibase, N, HcInterruptEnable, *((uint32_t *)&IR));

	//	Enable Execution Lists and Transition to UsbOperational State
	OHCIHcControlRegister_t control = {0};
	OHCIReadU32(acpibase, N, HcControl, (uint32_t *)&control);
	//	Set HostControllerFunctionalState = UsbOperational (10b)
	control.HostControllerFunctionalState = USBOperational;
	//	Enable Control, Bulk, and Periodic list processing
	control.PeriodicListEnable = true;
	control.ControlListEnable = true;
	control.BulkListEnable = true;
	OHCIWriteU32(acpibase, N, HcControl, *((uint32_t *)&control));

	//	Initialise Callback
	uint8_t Interrupt;
	uint8_t IST;
	IDTEntrySegmentSelector64 sselector;
	OHCIInterruptStackHeader *_temp = mcalloc(1, sizeof(OHCIInterruptStackHeader));
	if(AllocateInterruptVector(&Interrupt) && AllocateIST(&IST, &sselector)){
		ISRSetCallback(acpibase, Interrupt, Privilege, IST, _temp, sselector, false, &OHCIHeadDoneISR);}

	//	Power On Root Hub Ports
	OHCIHcRootHubDescriptorARegister_t rh_desc_a = {0};
	OHCIReadU32(acpibase, N, HcRootHubDescriptorA, (uint32_t *)&rh_desc_a);
	//	SetGlobalPower: Power on all ports
	if(rh_desc_a.NoPowerSwitching == 0){
		rh_desc_a.PowerSwitchingMode = true;
		OHCIWriteU32(acpibase, N, HcRootHubStatus, (uint32_t *)&rh_desc_a);
	}
	return true;
}

OHCIEndpointDescriptor_t *OHCIFindOrAppendED(void *acpibase, uint32_t N, 
	uint8_t deviceaddress, uint8_t endpointaddress, uint16_t max_packet_size, bool is_low_speed
){
	// 1. Fetch physical pointer to Control Head ED
	uint32_t head_phys = 0;
	OHCIReadU32(acpibase, N, HcControlHeadEndpointDescriptor, &head_phys);

	OHCIEndpointDescriptor_t *prev_ed = NULL;
	uint32_t curr_phys = head_phys & ~0xFU;

	//	Walk existing ED chain to find an idle/matching descriptor
	while(curr_phys != 0){
		OHCIEndpointDescriptor_t *ed = (OHCIEndpointDescriptor_t *)MapVirtual(curr_phys);
		if(!ed){break;}

		// Head TD pointer == Tail TD pointer indicates the queue is empty/completed
		uint32_t td_head_phys = ed->TransferDescriptorQueueHead << 4, 
				td_tail_phys = ed->TransferDescriptorQueueTail & ~0xFU;
		bool is_completed = (td_head_phys == td_tail_phys), 
			is_match = (ed->FunctionAddress == deviceaddress) && (ed->EndpointAddress == endpointaddress);

		//	Reuse ED if it matches our endpoint target or if its queue is finished
		if(is_match || is_completed){
			//	Temporarily stall hardware processing during update
			ed->Skip = 1;
			ed->FunctionAddress = deviceaddress & 0x7F;
			ed->EndpointAddress = endpointaddress & 0x0F;
			ed->LowSpeedEndpoint = is_low_speed ? 1 : 0;
			ed->MaximumPacketSize = max_packet_size & 0x7FF;
			ed->QueueHalted = 0;
			
			//	Resume execution
			ed->Skip = 0;
			return ed;
		}

		prev_ed = ed;
		curr_phys = ed->NextEndpointDescriptor & ~0xFU;
	}

	//	No available EDs found — allocate a new ED & required dummy tail TD
	OHCIEndpointDescriptor_t *new_ed = AllocateAlignedPagesFromRange(NULL, UINT32_MAX, 
		sizeof(OHCIEndpointDescriptor_t), (ReadWritable | SupervisorMode), 0x00, 16);
	OHCITransferDescriptor_t *dummy_td = AllocateAlignedPagesFromRange(NULL, UINT32_MAX, 
		sizeof(OHCITransferDescriptor_t), (ReadWritable | SupervisorMode), 0x00, 16);
	if(!new_ed || !dummy_td){return NULL;}

	memset(new_ed, 0, sizeof(OHCIEndpointDescriptor_t));
	memset(dummy_td, 0, sizeof(OHCITransferDescriptor_t));

	uint32_t dummy_phys = (uint32_t)(uintptr_t)MapPhysical(dummy_td), 
			new_ed_phys = (uint32_t)(uintptr_t)MapPhysical(new_ed);

	//	Initialize ED fields
	new_ed->FunctionAddress = deviceaddress & 0x7F;
	new_ed->EndpointAddress = endpointaddress & 0x0F;
	new_ed->DataFlow = 0; // Direction controlled by TD
	new_ed->LowSpeedEndpoint = is_low_speed ? 1 : 0;
	new_ed->Skip = 0;
	new_ed->IsochronousTransfers = 0;
	new_ed->MaximumPacketSize = max_packet_size & 0x7FF;
	new_ed->TransferDescriptorQueueTail = dummy_phys;
	new_ed->TransferDescriptorQueueHead = dummy_phys >> 4;
	new_ed->NextEndpointDescriptor = 0;

	//	Link into queue schedule
	if(prev_ed){prev_ed->NextEndpointDescriptor = new_ed_phys;}else
	{OHCIWriteU32(acpibase, N, HcControlHeadEndpointDescriptor, new_ed_phys);}

	return new_ed;
}

bool OHCISendControlCommand(
	void *acpibase, uint32_t N, uint8_t dev_addr, 
	uint16_t max_packet_size, USBControlRequest_t *req, 
	void *data_buffer, bool is_low_speed, CommonMutex Mtx
){
	if(!req){return false;}
	//	Locate or create Control Endpoint Descriptor (EP0)
	OHCIEndpointDescriptor_t *ed = OHCIFindOrAppendED(acpibase, N, dev_addr, 0, max_packet_size, is_low_speed);
	if(!ed){return false;}

	bool has_data = (req->wLength > 0), 
		is_in = (req->bmRequestType & 0x80) != 0;

	//	Allocate 16-byte aligned physical descriptors for TD chain + dummy tail
	OHCITransferDescriptor_t *td_setup = AllocateAlignedPagesFromRange(NULL, UINT32_MAX, sizeof(OHCITransferDescriptor_t), (ReadWritable | SupervisorMode), 0x00, 16), 
							*td_data = has_data ? AllocateAlignedPagesFromRange(NULL, UINT32_MAX, sizeof(OHCITransferDescriptor_t), (ReadWritable | SupervisorMode), 0x00, 16) : NULL, 
							*td_status = AllocateAlignedPagesFromRange(NULL, UINT32_MAX, sizeof(OHCITransferDescriptor_t), (ReadWritable | SupervisorMode), 0x00, 16), 
							*td_dummy = AllocateAlignedPagesFromRange(NULL, UINT32_MAX, sizeof(OHCITransferDescriptor_t), (ReadWritable | SupervisorMode), 0x00, 16);

	if(!td_setup || (has_data && !td_data) || !td_status || !td_dummy){return false;}

	memset(td_setup, 0, sizeof(OHCITransferDescriptor_t));
	if(has_data) memset(td_data, 0, sizeof(OHCITransferDescriptor_t));
	memset(td_status, 0, sizeof(OHCITransferDescriptor_t));
	memset(td_dummy, 0, sizeof(OHCITransferDescriptor_t));

	uint32_t phys_setup = (uint32_t)(uintptr_t)MapPhysical(td_setup), 
			phys_data = has_data ? (uint32_t)(uintptr_t)MapPhysical(td_data) : 0, 
			phys_status = (uint32_t)(uintptr_t)MapPhysical(td_status), 
			phys_dummy = (uint32_t)(uintptr_t)MapPhysical(td_dummy);

	uint32_t phys_req = (uint32_t)(uintptr_t)MapPhysical(req), 
			phys_buf = data_buffer ? (uint32_t)(uintptr_t)MapPhysical(data_buffer) : 0;

	//	Populate SETUP Stage TD (DATA0 toggle)
	td_setup->PreviousPacketErrorDisable = 1;
	//	00b = SETUP
	td_setup->TransferDirection = 0b00;
	//	111b = No interrupt
	td_setup->FrameDelay = 7;
	//	10b = DATA0
	td_setup->DataToggle = 2;
	//	Active / Not Accessed
	td_setup->LastTransactionStataus = 0xF;
	td_setup->BufferPointer = phys_req;
	td_setup->NextTransferDescriptor = has_data? phys_data: phys_status;
	td_setup->BufferTipPointer = phys_req + sizeof(USBControlRequest_t) - 1;

	//	Populate DATA Stage TD (DATA1 toggle, if payload exists)
	if(has_data){
		td_data->PreviousPacketErrorDisable = 1;
		//	10b = IN, 01b = OUT
		td_data->TransferDirection = is_in ? 2 : 1;
		td_data->FrameDelay = 7;
		td_data->DataToggle = 3;
		td_data->LastTransactionStataus = 0xF;
		td_data->BufferPointer = phys_buf;
		td_data->NextTransferDescriptor = phys_status;
		td_data->BufferTipPointer = phys_buf + req->wLength - 1;
	}

	//	Populate STATUS Stage TD (DATA1 toggle, Handshake direction)
	td_status->PreviousPacketErrorDisable = 1;
	//	10b = IN, 01b = OUT
	td_status->TransferDirection = !has_data || !is_in ? 2 : 1;
	td_status->FrameDelay = 0;
	td_status->DataToggle = 3;
	td_status->LastTransactionStataus = 0xF;
	td_status->BufferPointer = 0;
	td_status->NextTransferDescriptor = phys_dummy;
	td_status->BufferTipPointer = 0;

	//	Enqueue TD chain into Endpoint Descriptor
	ed->Skip = 1;
	ed->TransferDescriptorQueueHead = phys_setup >> 4;
	ed->TransferDescriptorQueueTail = phys_dummy;
	ed->QueueHalted = 0;
	ed->Skip = 0;

	//	Notify Host Controller of Control List work
	OHCIHcCommandStatusRegister_t cmd = {.ControlListFilled = true};
	OHCIReadU32(acpibase, N, HcCommandStatus, (uint32_t *)&cmd);
	cmd.ControlListFilled = true;
	OHCIWriteU32(acpibase, N, HcCommandStatus, *((uint32_t *)&cmd));

	return (td_status->LastTransactionStataus == 0);
}