#pragma once

#include "./kernel/lib32/generic/standard.h"
#include "./kernel/lib32/stdkernel/Interrupt/interrupt.h"

#define PICM_PORTCMD        0x20
#define PICM_PORTDATA       0x21
#define PICS_PORTCMD        0xA0
#define PICS_PORTDATA       0xA1
#define PICSendSpecificEOI 	PICSendSEOI

#define PIC_MAXIRQ			16

#define PICB_REMAPOFFSET		0x20
#define PICM_REMAPOFFSET		0x20
#define PICS_REMAPOFFSET		0x28

#define ReadInRequestReg(MASTER, SLAVE)    \
    uint16_t temp = PICReadIRQRequestReg(); \
    MASTER = (temp >> 8) & 0xFF;            \
    SLAVE = temp & 0xFF;
#define ReadIRQRequestReg(MASTER, SLAVE)    \
    uint16_t temp = PICReadIRQServiceReg(); \
    MASTER = (temp >> 8) & 0xFF;            \
    SLAVE = temp & 0xFF;

typedef enum PIC_ICW1{
    // Set Control Word as ICW4
    PIC_ICW1_ICW4 =      	    0x01,
    // If set, only 1 PIC. Otherwise a Slave PIC attached to Master PIC
    PIC_ICW1_SINGLE =           0x04,
    // Call Adress Interval. Set; 4, Unset; 8
	PIC_ICW1_INTRVL4 =          0x04,
	PIC_ICW1_INTRVL8 =          0x04,
    // If set, operate in Level-Triggered mode, Otherwise in Edge-Triggered Mode
    PIC_ICW1_LVL =       	    0x08,
    // Is Set, Initialise the PIC with the passed Word
    PIC_ICW1_INIT =       	    0x10
}PIC_ICW1;

typedef enum PIC_ICW4{
    // Set; PIC in 8086(x86) Mode. Otherwise in MCS-80/86 Mode
    PIC_ICW4_8086 =      	        0x01,
    // Set; EOI Automatically generated by PIC. Otherwise, signal generated by CPU
    PIC_ICW4_AEOI =                 0x02,
    // If Buffered is Set. Set; PIC is Buffer Master, Otherwise is Buffer Slave
	PIC_ICW4_BFMASTER =             0x04,
    // If Buffered is Set. Set; PIC is Buffer Slave, Otherwise is Buffer Master
	PIC_ICW4_BFSLAVE =              0x00,
    // Set; Operates in Buffered Mode
    PIC_ICW4_BUFFERED =       	    0x08,
    // Specially Fully-Nested Mode, beneficial in large cascading systems.
    PIC_ICW4_SFNM =       	        0x10
}PIC_ICW4;

typedef enum PIC_CMD{
    PIC_CMD_NONSPEC_EOI =           0x20,
	// Use specific EOI,shoud use PIC_SPECEOI macro
	PIC_CMD_SPEC_EOI =           	0x60,
	PIC_CMD_READISR = 				0x0B,
	PIC_CMD_READIRR = 				0x0A,
}PIC_CMD;
#define PIC_SPECEOI(irq) (PIC_CMD_SPEC_EOI | ((irq) & 0x7))

typedef struct PICOut{
    uint8_t PICMOut,
            PICSOut;
}PACKEDSTRUCT PICOut;

void PICInit(uint8_t offsetPIC1, uint8_t offsetPIC2);
void PICMask(uint32_t irq, bool toggle);
PICOut PICReadIRQServiceReg();
PICOut PICReadInRequestReg();
void ASMCALL PICSendSEOI(uint32_t irq);
void PICDisable();

void IRQInit();

typedef void (*IRQHandler)(InterruptFrame *in);
void RegIRQHandler(uint32_t irq, uint8_t ring, IRQHandler handler);
